### ISSUE TITLE
Remove ValidatorFilter 

### ISSUE THREAD

**Issue by ddeboer** [portphp/portphp#43]
We already have ValidatorStep. Is there any reason we still need the ValidatorFilter?

**Comment by borNfreee** [comment]
Why do you think it's not needed?

1. First of all, it allows to throw exceptions with useful information about failed lines
2. it allows to handle filtering using Validator
3. please read #42

**Comment by Baachi** [comment]
I'm not really sure why i created the `ValidatorFilter` and the `ValidatorStep`, but i think the `ValidatorFilter` was only created for "BC" reason, so old users has less hassle to migrate.
I see currently no reason why we should kept the `ValidatorFilter`. 

@borNfreee And yes you are correct, this was the main idea behind this change.

**Comment by magedan** [comment]
I'n not sure if it's an issue or not, but currently there is different behaviour of the `ValidatorStep` and `ValidatorFilter`. Everything works as expected with `ValidatorFilter` (at least, as expected by me) in the following abstract example (assuming Symfony console command context):

```php
$reader = new CsvReader(new \SplFileObject($path));
$table = new Table($output);
$filterStep = new FilterStep();
$validatorFilter = new ValidatorFilter($this->getContainer()->get('validator'));

$filterStep->add($validatorFilter);

// just a sample constraint
$validatorFilter->add(1, new Assert\GreaterThan(1));
$validatorFilter->setStrict(false);
$validatorFilter->throwExceptions(false);

$workflow = new Workflow($reader);

$workflow
    ->addWriter(new TableWriter($table))
    ->addStep($filterStep)
    ->process();
```
Table renders all valid rows and if I call `$validatorFilter->getViolations()` I get a list of `GreaterThan` constraints with correct property paths.

On the other hand, consider the same implementation using `ValidatorStep`:
```php
$reader = new CsvReader(new \SplFileObject($path));
$table = new Table($output);
$validatorStep = new ValidatorStep($this->getContainer()->get('validator'));

$validatorStep->add(1, new Assert\GreaterThan(1));
$validatorStep->throwExceptions(false);

$workflow = new Workflow($reader);

$workflow
    ->addWriter(new TableWriter($table))
    ->addStep($validatorStep)
    ->process();
```

This will result in `Collection` constraint violation for every field other than `[1]` with the following message: "This field was not expected.".

I assume that's because of the following block in `ValidatorFilter`, but not really sure:
```php
        if (!$this->strict) {
            // Only validate properties which have an constaint.
            $temp = array_intersect(array_keys($item), array_keys($this->constraints));
            $item = array_intersect_key($item, array_flip($temp));
        }
```

Also, still not sure about recommended way of doing validation - should I use "filter" or "step"? Documentation is not quite verbose http://portphp.readthedocs.io/en/latest/workflow/#validatorstep 
@ddeboer please advice

**Comment by ddeboer** [comment]
It seems their is a valid use case for each of them:

* `ValidatorFilter` is used in `FilterStep`, to exclude items from being processed if they fail to match some validation constraints.
* `ValidatorStep` processes all items, passing them through a validator, collecting all validation failures or (optionally) throwing an exception on the first validation failure encountered.

@Baachi Is this correct?

**Comment by Baachi** [comment]
@ddeboer Yes this was the intention behind this (if i remember me correctly). 
The `ValidatorFilter` should be used to filter out some items and the `ValidatorFilter` should be used to validate the items before they get processed (or saved to the database). Because we never trust user input :P

**Comment by magedan** [comment]
@ddeboer @Baachi It's clear now, thank you for clarification!

**Comment by ddeboer** [comment]
I’m glad this is now clear for everyone – including myself. Thanks!

**Comment by fnagel** [comment]
Can somebody help me out how to use this? I'm struggling a little. Any help appreciated, see #67
